# Generated by Django 4.0.6 on 2022-08-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='autre_image',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
