# Generated by Django 4.0.6 on 2022-08-21 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitrine', '0002_alter_bien_autre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='recepteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
