# Generated by Django 4.0.6 on 2022-08-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_alter_messages_recepteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='raison',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='telephone',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='recepteur',
            field=models.CharField(max_length=100),
        ),
    ]
